### PR TITLE
video download support

### PR DESCRIPTION
**Pull request by xannor**
This adds support for vod_download from the camera and fixes the limitation of the search to only search against "logical" channels. It also adds some additional support classes to flesh out the search functionality.

(This is another issue, my 1 gen duo has separate sensors for each "lens" and needs to operate against the stream_channels, not the "logical" channels. I corrected this for the search but this also should be corrected in the motion sensors as well.)

### CODE REVIEW

**Comment by starkillerOG** [comment]
@xannor what do you mean by:

> this also should be corrected in the motion sensors as well

Do you mean there schould be 2 binary motion sensors in HomeAssistant?
I thought they were coupled and would always show the same for both lenses.

**Comment by xannor** [comment]
For the 1st gen yes as the cameras are independent. The second gen probably has different hardware. The only controls that seem bonded but are lens related are the floodlight and ir as calling for either channel affects both. But this is a side note and not something really pertaining to this PR, I was just pointing out my reasoning for changing the search protection.

**Comment by starkillerOG** [comment]
@xannor Thank you very much for this PR.
Sorry for taking a while to look at it.

I did not see major problems, but made some small tweaks that only concern styling, typing issues and writing some things in a more compact way or to allign them with the rest of the library.

Functionally there schould not be any diffrence.

I had trouble pushing the comments directly to your branch, therefore I had to make a new branch.

I already merged the code, see PR: https://github.com/starkillerOG/reolink_aio/pull/31

**Comment by starkillerOG** [comment]
Since the code of this PR has been merged, I will close it now.

I am planning to release a new reolink-aio version in a few days.
I want to add the firmware updates as suggested here: https://github.com/starkillerOG/reolink_aio/issues/30

**Pull request closed without merging**
